name: Test Build

# if the tag contains -test- the build is pushed into the build-test branch
# so skunkcrafts does not see it

on:
  workflow_dispatch:

jobs:
  build-linux-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # use oldest possible ubuntu version in order to avoid compatibility errors with libc
        os: [ubuntu-22.04, macos-14]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3

      - name: Get XPlane SDK + xplib
        shell: bash
        run: |
            SDK_VERSION=411
            curl -L "https://developer.x-plane.com/wp-content/plugins/code-sample-generation/sdk_zip_files/XPSDK${SDK_VERSION}.zip" -o "XPSDK${SDK_VERSION}.zip"
            unzip XPSDK${SDK_VERSION}.zip
            mv SDK ../
            git clone https://github.com/hotbso/xplib.git ../xplib

      - name: Build Executable
        shell: bash
        env:
          OS: ${{ matrix.os }}
        run: |
          TAG=${GITHUB_REF##*/}
          if [ ! -z "$TAG" ]; then
            echo "VERSION=$TAG" > version.mak
          fi

          if [[ $OS == "macos-"* ]]; then
            make -f Makefile.mac64
          else
            sudo apt-get -y install libcurl4-openssl-dev
            make -f Makefile.lin64
          fi

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            build/*.xpl

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            make
            git

      - uses: actions/checkout@v3

      - name: Get XPlane SDK + xplib
        shell: bash
        run: |
            SDK_VERSION=411
            curl -L "https://developer.x-plane.com/wp-content/plugins/code-sample-generation/sdk_zip_files/XPSDK${SDK_VERSION}.zip" -o "XPSDK${SDK_VERSION}.zip"
            unzip XPSDK${SDK_VERSION}.zip
            mv SDK ../
            git clone https://github.com/hotbso/xplib.git ../xplib

      - name: Build Windows binaries
        shell: msys2 {0}
        run: |
            TAG=${GITHUB_REF##*/}
            if [ ! -z "$TAG" ]; then
              echo "VERSION=$TAG" > version.mak
            fi
            make -f Makefile.mgw64

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: |
            build/*.xpl

  release:
    runs-on: ubuntu-latest
    needs: [build-linux-macos, build-windows]

    steps:
      - uses: actions/checkout@v3

      - name: setup crc32 tool
        shell: bash
        run: |
            sudo apt-get update
            sudo apt-get install -y libarchive-zip-perl
            TAG=${GITHUB_REF##*/}
            if [ -n "$TAG" ]; then
              echo "VERSION=$TAG" > version.mak
            fi

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./download

      - name: List artifacts
        shell: bash
        run: |
            pwd
            ls -lR ./download
